import { normalizeQboGlAccountKey } from "./taxQboGlNormalizer.js";

export const TAX_GL_RULE_VERSION = "bizzi-gl-2026-v4";
export const TAX_GL_RULE_SOURCE_REFERENCE = "Bizzi approved deterministic GL-to-tax mapping policy 2026";
export const TAX_GL_RULE_SOURCE_URL = "internal://bizzi/tax/gl-alias-rules/2026-v4";

export const TAX_GL_ALIAS_RULES = Object.freeze([
  rule("software_subscriptions_gl_v3", ["Software", "Software & Apps", "Subscriptions", "Computer Software", "SaaS", "Software Subscriptions", "Online Services"], "software_subscriptions", "fully_deductible", 100, false, 10, { type: "ordinary_expense", irs_category: "other_business_expense" }),
  rule("business_insurance_gl_v3", ["Insurance", "Business Insurance", "General Liability", "General Liability Insurance", "Commercial Insurance", "Workers Comp", "Workers Compensation", "Workers Compensation Insurance", "Contractor Insurance"], "business_insurance", "fully_deductible", 100, false, 12, { type: "ordinary_expense", irs_category: "insurance" }),
  rule("office_supplies_gl_v3", ["Office Supplies", "Office Expense", "Administrative Supplies", "Office Materials"], "office_supplies", "fully_deductible", 100, false, 20, { type: "ordinary_expense", irs_category: "office_expense" }),
  rule("job_materials_gl_v3", ["Materials", "Job Materials", "Construction Materials", "Building Materials", "Supplies & Materials", "Materials & Supplies", "Job Supplies", "Project Materials", "Direct Materials"], "job_materials", "fully_deductible", 100, false, 18, { type: "job_cost_materials", irs_category: "supplies" }),
  rule("generic_supplies_review_gl_v3", ["Supplies"], "supplies", "fully_deductible", 100, true, 42, { type: "supplies_review", classification_review_required: true }, "Confirm whether these are office supplies, job supplies, or materials."),
  rule("contract_labor_gl_v3", ["Subcontractors", "Subcontractor", "Subcontractor Expense", "Contract Labor", "Outside Labor", "Independent Contractors", "1099 Contractors", "Trade Partners"], "contract_labor", "fully_deductible", 100, false, 16, { type: "ordinary_expense", irs_category: "contract_labor" }),
  rule("small_consumable_tools_gl_v3", ["Small Tools", "Hand Tools", "Consumable Tools", "Tool Expense"], "small_tools", "fully_deductible", 100, false, 24, { type: "ordinary_expense", irs_category: "tools" }),
  rule("tools_small_equipment_review_gl_v3", ["Tools", "Small Equipment"], "small_tools", "needs_review", 0, true, 26, { type: "small_tools_review", capitalization_review_required: true }),
  rule("equipment_rental_gl_v3", ["Equipment Rental", "Equipment Rentals", "Tool Rental", "Tool Rentals", "Machinery Rental", "Rental Equipment"], "equipment_rental", "fully_deductible", 100, false, 22, { type: "rental_expense", irs_category: "rent" }),
  rule("vehicle_fuel_review_gl_v3", ["Fuel", "Gas", "Vehicle Fuel", "Auto Fuel", "Fuel Expense", "Gas & Fuel", "Automobile Expense", "Auto Expense"], "vehicle_expense", "needs_review", 0, true, 30, { type: "vehicle_expense", business_use_required: true }),
  rule("vehicle_repairs_review_gl_v3", ["Vehicle Maintenance", "Auto Maintenance", "Vehicle Repairs", "Auto Repairs", "Truck Repairs", "Truck Maintenance", "Fleet Maintenance", "Vehicle Repairs & Maintenance"], "vehicle_expense", "needs_review", 0, true, 30, { type: "vehicle_expense", business_use_required: true }),
  rule("parking_tolls_transportation_review_gl_v3", ["Parking", "Parking Fees", "Tolls", "Road Tolls", "Rideshare", "Uber", "Lyft", "Uber & Lyft", "Lyft Uber", "Local Transportation", "Transportation"], "travel_transportation", "needs_review", 0, true, 34, { type: "travel_transportation", business_purpose_required: true }),
  rule("repairs_maintenance_review_gl_v3", ["Repairs", "Repairs & Maintenance", "Equipment Repairs", "Equipment Maintenance", "Machinery Repairs", "Property Repairs", "Maintenance Expense"], "repairs_maintenance", "fully_deductible", 100, true, 32, { type: "ordinary_expense", capitalization_review_required: true }),
  rule("licenses_permits_inspections_gl_v3", ["Permits", "Business Licenses", "Licenses", "Licenses & Permits", "Inspection Fees", "Permit Fees", "Building Permits", "Contractor Licenses"], "licenses_permits", "fully_deductible", 100, false, 22, { type: "ordinary_expense", irs_category: "taxes_and_licenses" }),
  rule("waste_disposal_job_costs_gl_v3", ["Dump Fees", "Waste Disposal", "Debris Removal", "Trash Removal", "Hauling", "Disposal Fees", "Landfill Fees", "Jobsite Cleanup"], "waste_disposal_job_costs", "fully_deductible", 100, false, 22, { type: "job_cost", irs_category: "disposal_fees" }),
  rule("payment_processing_fees_gl_v3", ["Merchant Fees", "Merchant Processing Fees", "Processing Fees", "Credit Card Fees", "Credit Card Processing Fees", "Payment Processing Fees", "Stripe Fees", "Square Fees"], "payment_processing_fees", "fully_deductible", 100, false, 14, { type: "ordinary_expense", irs_category: "commissions_and_fees" }),
  rule("bank_service_fees_gl_v3", ["Bank Fees", "Bank Charges", "Service Charges", "Bank Service Charges", "Monthly Bank Fees"], "bank_fees", "fully_deductible", 100, false, 14, { type: "ordinary_expense", irs_category: "bank_fees" }),
  rule("legal_services_gl_v3", ["Legal", "Legal Fees", "Attorney Fees", "Legal Services"], "legal_professional", "fully_deductible", 100, false, 18, { type: "ordinary_expense", irs_category: "legal_and_professional_fees" }),
  rule("accounting_services_gl_v3", ["Accounting", "Accounting Fees", "Bookkeeping", "Bookkeeping Fees", "Tax Preparation", "CPA Fees"], "legal_professional", "fully_deductible", 100, false, 18, { type: "ordinary_expense", irs_category: "legal_and_professional_fees" }),
  rule("professional_services_review_gl_v3", ["Professional Fees", "Professional Services", "Consulting Fees", "Consultants"], "legal_professional", "fully_deductible", 100, true, 28, { type: "ordinary_expense", review_required: true }),
  rule("advertising_marketing_gl_v3", ["Advertising", "Marketing", "Advertising & Marketing", "Digital Advertising", "Online Advertising", "Website Advertising", "Lead Generation", "Promotional Expense"], "advertising_marketing", "fully_deductible", 100, false, 20, { type: "ordinary_expense", irs_category: "advertising" }),
  rule("business_rent_gl_v3", ["Office Rent", "Shop Rent", "Warehouse Rent", "Business Rent", "Yard Rent", "Storage Rent", "Commercial Rent"], "rent_lease", "fully_deductible", 100, false, 20, { type: "ordinary_expense", irs_category: "rent" }),
  rule("generic_rent_review_gl_v3", ["Rent", "Rent Expense", "Lease Expense"], "rent_lease", "needs_review", 0, true, 34, { type: "rent_review", business_use_required: true }),
  rule("business_premises_utilities_gl_v3", ["Shop Utilities", "Office Utilities", "Warehouse Utilities", "Jobsite Utilities", "Commercial Utilities"], "utilities", "fully_deductible", 100, false, 22, { type: "ordinary_expense", irs_category: "utilities" }),
  rule("mixed_utilities_review_gl_v3", ["Utilities", "Electric", "Electricity", "Water", "Internet", "Internet Expense", "Phone", "Phone Bill", "Telephone", "Cell Phone", "Mobile Phone"], "utilities", "needs_review", 0, true, 36, { type: "utilities_review", business_use_required: true }),
  rule("safety_supplies_gl_v3", ["Safety Equipment", "PPE", "Personal Protective Equipment", "Safety Supplies", "Protective Gear", "Jobsite Safety"], "safety_supplies", "fully_deductible", 100, false, 20, { type: "ordinary_expense", irs_category: "safety_supplies" }),
  rule("uniforms_work_clothing_review_gl_v3", ["Uniforms", "Work Uniforms", "Branded Apparel", "Protective Clothing", "Work Clothing", "Workwear"], "uniforms_work_clothing", "needs_review", 0, true, 38, { type: "uniforms_review", substantiation_required: true }),
  rule("education_training_review_gl_v3", ["Training", "Employee Training", "Continuing Education", "Certifications", "Professional Development", "Safety Training"], "education_training", "needs_review", 0, true, 38, { type: "education_training_review", business_purpose_required: true }),
  rule("business_travel_review_gl_v3", ["Travel", "Business Travel", "Lodging", "Hotels", "Hotel", "Airfare", "Flights"], "business_travel", "needs_review", 0, true, 36, { type: "business_travel", business_purpose_required: true }),
  rule("business_meals_review_gl_v3", ["Meals", "Business Meals", "Client Meals", "Travel Meals", "Meals & Entertainment", "Meals and Entertainment"], "business_meals", "partially_deductible", 50, true, 32, { type: "ordinary_expense", limitation: "50_percent_meals", substantiation_required: true }),
  rule("depreciation_review_gl_v3", ["Depreciation Expense", "Accumulated Depreciation Expense", "Depreciation"], "depreciation", "fully_deductible", 100, true, 40, { type: "depreciation_expense", fixed_asset_reconciliation_required: true }),
  rule("fixed_asset_capitalizable_gl_v3", ["Equipment Purchase", "Equipment Purchases", "Machinery Purchase", "Machinery", "Vehicles", "Vehicle Purchase", "Construction Equipment", "Fixed Assets", "Furniture & Equipment"], "fixed_asset_capitalizable", "capitalizable", 0, true, 12, { type: "capitalizable", depreciation_required: true }),
  rule("loan_interest_review_gl_v3", ["Interest Expense", "Loan Interest", "Business Loan Interest", "Equipment Loan Interest", "Vehicle Loan Interest"], "interest_expense", "fully_deductible", 100, true, 34, { type: "ordinary_expense", irs_category: "interest", limitations_review_required: true }),
  rule("loan_principal_exclusion_gl_v3", ["Loan Principal", "Principal Payment", "Loan Payment Principal", "Debt Principal", "Note Payable Payment"], "liability_payment", "balance_sheet", 0, false, 4, { type: "balance_sheet", component: "loan_principal" }),
  rule("generic_loan_payment_review_gl_v3", ["Loan Payment", "Business Loan Payment", "Debt Payment"], "debt_payment", "needs_review", 0, true, 44, { type: "debt_payment_review", principal_interest_split_required: true }, "Separate principal from potentially deductible interest."),
  rule("owner_activity_exclusion_gl_v3", ["Owner Draw", "Owner Draws", "Owner Distribution", "Owner Distributions", "Partner Distribution", "Shareholder Distribution", "Personal Expense", "Personal Expenses", "Owner Contribution", "Owner Contributions"], "owner_activity", "balance_sheet", 0, false, 4, { type: "balance_sheet", component: "owner_activity" }),
  rule("transfer_credit_card_payment_exclusion_gl_v3", ["Transfer", "Transfers", "Bank Transfer", "Account Transfer", "Credit Card Payment", "Credit Card Payments", "Payment to Credit Card"], "transfer", "balance_sheet", 0, false, 4, { type: "balance_sheet", component: "transfer_or_credit_card_payment" }),
  rule("payroll_wages_gl_v3", ["Wages", "Payroll", "Gross Wages", "Employee Wages", "Salaries"], "wages_payroll", "fully_deductible", 100, false, 24, { type: "ordinary_expense", irs_category: "wages" }),
  rule("employer_payroll_taxes_gl_v3", ["Payroll Taxes", "Employer Payroll Taxes"], "payroll_taxes", "fully_deductible", 100, false, 24, { type: "ordinary_expense", irs_category: "employer_payroll_taxes" }),
  rule("revenue_exclusion_gl_v3", ["Income", "Sales", "Sales Income", "Service Revenue", "Contract Revenue", "Construction Income", "Job Revenue"], "revenue", "balance_sheet", 0, false, 2, { type: "revenue", ordinaryExpense: false }),
  rule("liability_balance_sheet_exclusion_gl_v3", ["Sales Tax Payable", "Payroll Liabilities", "Credit Card Payable", "Accounts Payable", "Loans Payable"], "balance_sheet_movement", "balance_sheet", 0, false, 2, { type: "balance_sheet", component: "liability_movement" }),
  rule("cogs_parent_account_gl_v4", ["Cost of Goods Sold", "Costs of Goods Sold", "COGS", "Cost of Sales", "Costs of Sales", "Direct Costs", "Direct Job Costs", "Job Costs", "Construction Costs", "Project Costs", "Service Costs", "Cost of Revenue"], "cost_of_goods_sold", "fully_deductible", 100, false, 11, {
    type: "cogs_candidate",
    reporting_destination: "schedule_c_part_iii_or_form_1125_a_candidate",
    ordinaryExpense: false,
    allowed_qbo_account_type_keys: ["cost of goods sold"],
    negative_aliases: ["Gross Profit", "Gross Margin", "Cost Estimate", "Cost Reimbursement", "Reimbursed Costs", "Customer Reimbursement", "Cost Allocation", "Other Income", "Cost of Goods Sold Adjustment", "Inventory Asset", "Opening Inventory", "Closing Inventory", "Equipment Purchase", "Fixed Assets", "Loan Costs", "Startup Costs"],
  }, "Costs posted to a verified QuickBooks cost-of-goods-sold account.", { qboAccountTypeKeys: ["Cost of Goods Sold"] }),
  rule("inventory_purchases_review_gl_v4", ["Inventory Purchases", "Purchases - Inventory", "Purchases for Resale", "Merchandise Purchases", "Materials Inventory", "Job Materials Inventory", "Construction Materials Inventory", "Raw Materials", "Raw Materials Purchases", "Parts Inventory", "Parts Purchases", "Stock Purchases", "Resale Inventory", "Inventory Materials", "Inventory Clearing"], "inventory_purchases", "needs_review", 0, true, 17, {
    type: "inventory_cogs_review",
    reporting_destination: "inventory_or_cogs_destination_not_determined",
    allowed_qbo_account_type_keys: ["cost of goods sold", "other current asset", "expense"],
    review_question: "Were these materials used on completed jobs this year, or are they still held for future jobs?",
    negative_aliases: ["Office Supplies", "General Supplies", "Safety Supplies", "Small Tools", "Fixed Assets", "Equipment", "Inventory Sale", "Inventory Income", "Customer Deposit", "Owner Contribution", "Inventory Loan", "Inventory Reimbursement"],
  }, "Purchases that may need to remain in inventory until the related materials or goods are used or sold."),
  rule("inventory_variance_review_gl_v4", ["Inventory Variance", "Purchase Returns and Allowances"], "inventory_purchases", "needs_review", 0, true, 13, {
    type: "inventory_contra_or_variance_review",
    reporting_destination: "inventory_or_cogs_destination_not_determined",
    allowed_qbo_account_type_keys: ["cost of goods sold", "other current asset", "expense"],
    signed_contra_review_required: true,
  }, "Inventory variances or purchase returns need review before tax treatment is confirmed."),
  rule("equipment_fuel_gl_v4", ["Equipment Fuel", "Machinery Fuel", "Jobsite Fuel", "Job Site Fuel", "Generator Fuel", "Diesel - Equipment", "Equipment Diesel", "Off-Road Fuel", "Off Road Fuel", "Fuel - Machinery", "Fuel - Equipment", "Heavy Equipment Fuel", "Small Equipment Fuel", "Landscaping Equipment Fuel", "Mower Fuel", "Fuel and Lubricants - Equipment", "Equipment Gas and Oil"], "equipment_fuel", "fully_deductible", 100, false, 19, {
    type: "equipment_fuel",
    reporting_destination: "schedule_c_operating_or_direct_job_cost_candidate",
    allowed_qbo_account_type_keys: ["expense", "cost of goods sold"],
    excludes_vehicle_method: true,
    negative_aliases: ["Gas", "Gasoline", "Fuel", "Auto Fuel", "Vehicle Fuel", "Fleet Fuel", "Car Fuel", "Truck Fuel", "Mileage", "Fuel Reimbursement", "Fuel Surcharge Income", "Customer Fuel Reimbursement", "Heating Fuel", "Natural Gas Utility", "Oil and Gas Revenue"],
  }, "Fuel for business equipment rather than a road vehicle."),
  rule("shipping_postage_operating_gl_v4", ["Shipping", "Shipping Expense", "Shipping and Delivery", "Delivery Expense", "Delivery Fees", "Courier Expense", "Courier and Delivery", "Postage", "Postage and Delivery", "Postage and Shipping", "Freight-Out", "Freight Out", "Outbound Freight"], "shipping_freight_delivery", "fully_deductible", 100, false, 21, {
    type: "postage_operating",
    reporting_destination: "schedule_c_operating_expense_candidate",
    allowed_qbo_account_type_keys: ["expense"],
    negative_aliases: ["Shipping Income", "Delivery Income", "Freight Income", "Shipping Reimbursement", "Customer Delivery Reimbursement", "Freight Surcharge Income", "Delivery Driver Wages", "Vehicle Expense", "Inventory Asset", "Equipment Freight Income", "Sales"],
  }, "Shipping and delivery costs. Inbound freight may need to be included with inventory or job costs."),
  rule("shipping_inbound_freight_review_gl_v4", ["Freight-In", "Freight In", "Inbound Freight", "Materials Delivery", "Job Materials Delivery"], "shipping_freight_delivery", "needs_review", 0, true, 18, {
    type: "inbound_freight_cogs",
    reporting_destination: "inventory_or_cogs_destination_not_determined",
    allowed_qbo_account_type_keys: ["expense", "cost of goods sold", "other current asset"],
    review_question: "Was this inbound freight tied to inventory, job materials, or ordinary delivery?",
  }, "Shipping and delivery costs. Inbound freight may need to be included with inventory or job costs."),
  rule("shipping_equipment_delivery_review_gl_v4", ["Equipment Delivery"], "shipping_freight_delivery", "capitalizable", 0, true, 13, {
    type: "equipment_delivery_capitalization_review",
    reporting_destination: "form_4562_candidate",
    allowed_qbo_account_type_keys: ["expense", "fixed asset"],
    capitalization_review_required: true,
  }, "Equipment delivery may need to be included in the cost of equipment placed in service."),
  rule("shipping_generic_freight_review_gl_v4", ["Freight", "Freight Expense", "Trucking and Freight"], "shipping_freight_delivery", "needs_review", 0, true, 37, {
    type: "ambiguous_freight_review",
    reporting_destination: "not_yet_determined",
    allowed_qbo_account_type_keys: ["expense", "cost of goods sold"],
  }, "Shipping and delivery costs. Inbound freight may need to be included with inventory or job costs."),
  rule("other_business_taxes_review_gl_v4", ["Business Taxes", "State Business Taxes", "Local Business Taxes", "Franchise Tax", "Franchise Taxes", "Gross Receipts Tax", "Business Property Tax", "Personal Property Tax - Business", "Tangible Personal Property Tax", "Excise Tax Expense", "Occupational Tax", "Privilege Tax", "Local Business Tax", "County Business Tax", "City Business Tax", "Use Tax Expense", "Non-Payroll Taxes", "Other Business Taxes"], "other_business_taxes", "needs_review", 0, true, 29, {
    type: "business_tax_review",
    reporting_destination: "entity_specific_destination_not_determined",
    allowed_qbo_account_type_keys: ["expense"],
    review_question: "What type of tax was this payment for?",
    negative_aliases: ["Federal Income Tax", "Personal Income Tax", "Estimated Income Tax", "State Income Tax Payment", "Owner Tax Payment", "Sales Tax Payable", "Sales Tax Collected", "Payroll Tax Payable", "Employee Withholding", "Federal Withholding", "State Withholding", "FICA Payable", "Medicare Payable", "FUTA Payable", "SUTA Payable", "Tax Refund", "Tax Reimbursement", "Tax Penalty", "IRS Penalty", "Late Filing Penalty", "Interest and Penalties", "Property Tax Escrow", "Customer Sales Tax", "Payroll Taxes", "Licenses and Permits"],
  }, "Business tax payments that require the tax type to be identified before treatment is confirmed."),
  rule("commissions_referral_fees_gl_v4", ["Commissions", "Commission Expense", "Sales Commissions", "Sales Commission Expense", "Referral Fees", "Referral Fee Expense", "Finders Fees", "Finder Fees", "Lead Referral Fees", "Broker Commissions", "Agent Commissions", "Sales Agent Fees", "Dealer Commissions", "Subcontractor Commissions", "Performance Commissions", "Affiliate Commissions", "Affiliate Fees"], "commissions_referral_fees", "fully_deductible", 100, false, 23, {
    type: "ordinary_expense",
    irs_category: "commissions_and_fees",
    allowed_qbo_account_type_keys: ["expense"],
    information_reporting_review_supported: true,
    negative_aliases: ["Commission Income", "Sales Commission Income", "Referral Income", "Affiliate Income", "Broker Income", "Employee Commission Wages", "Payroll", "Bonuses", "Merchant Fees", "Bank Fees", "Loan Origination Fees", "Real Estate Purchase Commission", "Asset Acquisition Commission", "Customer Refund", "Owner Draw", "Fees"],
  }, "Business commissions or referral fees paid to generate work or sales."),
  rule("employee_benefits_gl_v4", ["Employee Benefits", "Employee Benefit Programs", "Employee Health Insurance", "Group Health Insurance", "Employee Medical Insurance", "Employee Dental Insurance", "Employee Vision Insurance", "Group-Term Life Insurance", "Employee Life Insurance", "Employee Disability Insurance", "Employee Assistance Program", "Dependent Care Assistance", "Employee Welfare Benefits", "Employee Wellness Benefits", "Employer HSA Contributions", "Employer Benefit Contributions", "Workers Benefits"], "employee_benefits", "fully_deductible", 100, false, 25, {
    type: "employee_benefits",
    reporting_destination: "entity_specific_employee_benefit_candidate",
    allowed_qbo_account_type_keys: ["expense"],
    owner_employee_distinction_required_when_ambiguous: true,
    negative_aliases: ["Owner Health Insurance", "Shareholder Health Insurance", "Partner Health Insurance", "Self-Employed Health Insurance", "Member Health Insurance", "Owner Life Insurance", "Key Person Life Insurance", "Workers Compensation", "Retirement Contributions", "Pension Expense", "Profit Sharing", "Employee Loans", "Employee Advances", "Payroll Liabilities", "Employee Withholding", "Employee Reimbursement", "Customer Benefits", "Government Benefits Income"],
  }, "Employer-paid employee benefits, excluding owner-only benefits and retirement-plan contributions."),
  rule("employee_benefits_review_gl_v4", ["Fringe Benefits", "Employee Reimbursements - Benefits", "Benefits"], "employee_benefits", "needs_review", 0, true, 39, {
    type: "employee_benefits_review",
    reporting_destination: "entity_specific_employee_benefit_candidate",
    allowed_qbo_account_type_keys: ["expense"],
    review_question: "Was this benefit for employees, an owner/shareholder, or both?",
  }, "Employer-paid employee benefits, excluding owner-only benefits and retirement-plan contributions."),
  rule("retirement_contributions_review_gl_v4", ["Employer Retirement Contributions", "Employer 401(k) Contributions", "Employer 401k Contributions", "Employer Pension Contributions", "Pension Expense", "Profit Sharing Contributions", "Employer Profit Sharing", "Employee Pension Plan Expense", "Retirement Plan Expense", "Employer SEP Contributions", "Employer SIMPLE Contributions", "Employer Matching Contributions", "401(k) Match", "401k Match", "Pension and Profit Sharing", "Qualified Plan Contributions"], "retirement_contributions", "needs_review", 0, true, 27, {
    type: "retirement_contribution_review",
    reporting_destination: "schedule_1_or_entity_specific_destination_not_determined",
    allowed_qbo_account_type_keys: ["expense"],
    beneficiary_scope: "unknown",
    contribution_type: "unknown",
    review_question: "Was this an employer contribution for employees, a contribution for an owner, or an employee amount withheld through payroll?",
    negative_aliases: ["401(k) Payable", "401k Payable", "Employee 401(k) Withholding", "Employee Retirement Withholding", "Retirement Plan Liability", "Pension Payable", "Owner Contribution", "Partner Contribution", "Member Contribution", "IRA Transfer", "Retirement Transfer", "Retirement Distribution", "Pension Income", "401(k) Loan", "401k Loan", "Employee Loan", "Payroll Clearing", "Benefit Payable", "Plan Administration Fees"],
  }, "Retirement-plan contributions requiring confirmation of whether they were for employees, owners, or payroll withholding."),
]);

export function buildTaxGlAliasDeductionRules({ taxYear = 2026, verifiedAt = "2026-09-10T00:00:00Z" } = {}) {
  return TAX_GL_ALIAS_RULES.map((item) => ({
    id: item.rule_code,
    business_id: null,
    scope: "global",
    rule_code: item.rule_code,
    tax_year: taxYear,
    jurisdiction: "federal",
    entity_type: null,
    bookkeeping_category: null,
    qbo_account_type: null,
    qbo_account_subtype: null,
    match_conditions: buildMatchConditions(item),
    tax_category: item.tax_category,
    deductibility_status: item.deductibility_status,
    default_deductible_percent: item.default_deductible_percent,
    treatment: item.treatment,
    requires_review: item.requires_review,
    priority: item.priority,
    explanation: item.explanation,
    source_reference: TAX_GL_RULE_SOURCE_REFERENCE,
    source_url: TAX_GL_RULE_SOURCE_URL,
    verified_at: verifiedAt,
    effective_from: `${taxYear}-01-01`,
    effective_to: `${taxYear}-12-31`,
    is_active: true,
    version: TAX_GL_RULE_VERSION,
    support_level: "verified",
  }));
}

function buildMatchConditions(item) {
  return Object.fromEntries(Object.entries({
    qbo_account_name_keys: item.aliasKeys,
    qbo_account_type_keys: item.qboAccountTypeKeys,
    qbo_account_subtype_keys: item.qboAccountSubtypeKeys,
  }).filter(([, value]) => Array.isArray(value) && value.length));
}

function rule(ruleCode, aliases, taxCategory, deductibilityStatus, percent, requiresReview, priority, treatment, explanation = null, options = {}) {
  return Object.freeze({
    rule_code: ruleCode,
    aliases: Object.freeze([...aliases]),
    aliasKeys: Object.freeze([...new Set(aliases.map(normalizeQboGlAccountKey))]),
    qboAccountTypeKeys: Object.freeze([...(options.qboAccountTypeKeys || []).map(normalizeQboGlAccountKey)]),
    qboAccountSubtypeKeys: Object.freeze([...(options.qboAccountSubtypeKeys || []).map(normalizeQboGlAccountKey)]),
    tax_category: taxCategory,
    deductibility_status: deductibilityStatus,
    default_deductible_percent: percent,
    requires_review: requiresReview,
    priority,
    treatment: Object.freeze(treatment),
    explanation: explanation || `Approved deterministic GL alias mapping for ${taxCategory}.`,
  });
}
