begin;

alter table public.gpt_messages
  add column if not exists message_role_position smallint,
  add column if not exists message_sequence bigint generated by default as identity;

update public.gpt_messages
set message_role_position = case
  when role = 'user' then 0
  when role in ('assistant', 'bizzy') then 1
  else 2
end
where message_role_position is null;

alter table public.gpt_messages
  alter column message_role_position set default 2,
  alter column message_role_position set not null;

alter table public.gpt_messages
  drop constraint if exists gpt_messages_role_position_check;
alter table public.gpt_messages
  add constraint gpt_messages_role_position_check
  check (message_role_position in (0, 1, 2));

create index if not exists gpt_messages_thread_conversation_order_idx
  on public.gpt_messages (
    thread_id,
    created_at desc,
    message_role_position desc,
    message_sequence desc
  )
  where message_kind = 'conversation';

drop function if exists public.match_bizzy_memory(uuid, uuid, public.vector, double precision, integer, text[]);
create function public.match_bizzy_memory(
  user_uuid uuid,
  business_uuid uuid,
  query_embedding public.vector,
  match_threshold double precision default 0.75,
  match_count integer default 3,
  tag_filter text[] default null
)
returns table(
  id uuid,
  input_text text,
  bizzy_response text,
  tags text[],
  kpis jsonb,
  similarity double precision,
  memory_kind text,
  policy_version text
)
language sql stable security definer
set search_path = pg_catalog, public
as $$
  select bm.id, bm.input_text, bm.bizzy_response, bm.tags, bm.kpis,
    1 - (bm.embedding <=> query_embedding) as similarity,
    bm.memory_kind, bm.policy_version
  from public.bizzy_memory bm
  where user_uuid is not null
    and business_uuid is not null
    and (
      exists (
        select 1
        from public.business_profiles bp
        where bp.id = business_uuid
          and bp.user_id = user_uuid
      )
      or exists (
        select 1
        from public.user_business_link ubl
        where ubl.business_id = business_uuid
          and ubl.user_id = user_uuid
      )
    )
    and bm.user_id = user_uuid
    and bm.business_id = business_uuid
    and bm.embedding is not null
    and bm.policy_version = 'durable-memory-v1'
    and bm.memory_kind in (
      'communication_preference',
      'operating_preference',
      'business_rule',
      'long_term_goal',
      'terminology_preference'
    )
    and (tag_filter is null or bm.tags && tag_filter)
    and (1 - (bm.embedding <=> query_embedding)) >= match_threshold
  order by bm.embedding <=> query_embedding asc
  limit match_count;
$$;

alter function public.match_bizzy_memory(uuid, uuid, public.vector, double precision, integer, text[]) owner to postgres;
revoke all on function public.match_bizzy_memory(uuid, uuid, public.vector, double precision, integer, text[]) from public, anon, authenticated;
grant execute on function public.match_bizzy_memory(uuid, uuid, public.vector, double precision, integer, text[]) to service_role;

commit;
